/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardInstitutionsRouteRouteImport } from './routes/dashboard/institutions/route'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'

const InstitutionsSubmissionsIndexLazyRouteImport = createFileRoute(
  '/institutions/submissions/',
)()
const InstitutionsDashboardIndexLazyRouteImport = createFileRoute(
  '/institutions/dashboard/',
)()
const DashboardUsersIndexLazyRouteImport =
  createFileRoute('/dashboard/users/')()
const DashboardTemplatesIndexLazyRouteImport = createFileRoute(
  '/dashboard/templates/',
)()
const DashboardSubmissionsIndexLazyRouteImport = createFileRoute(
  '/dashboard/submissions/',
)()
const DashboardProductsIndexLazyRouteImport = createFileRoute(
  '/dashboard/products/',
)()
const DashboardPhasesIndexLazyRouteImport =
  createFileRoute('/dashboard/phases/')()
const DashboardInstitutionsIndexLazyRouteImport = createFileRoute(
  '/dashboard/institutions/',
)()
const DashboardFormsIndexLazyRouteImport =
  createFileRoute('/dashboard/forms/')()
const DashboardSettingsNotificationsLazyRouteImport = createFileRoute(
  '/dashboard/settings/notifications',
)()
const DashboardSettingsDisplayLazyRouteImport = createFileRoute(
  '/dashboard/settings/display',
)()
const DashboardSettingsAppearanceLazyRouteImport = createFileRoute(
  '/dashboard/settings/appearance',
)()
const DashboardSettingsAccountLazyRouteImport = createFileRoute(
  '/dashboard/settings/account',
)()

const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstitutionsRouteRoute =
  DashboardInstitutionsRouteRouteImport.update({
    id: '/institutions',
    path: '/institutions',
    getParentRoute: () => DashboardRoute,
  } as any)
const InstitutionsSubmissionsIndexLazyRoute =
  InstitutionsSubmissionsIndexLazyRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => InstitutionsRoute,
  } as any).lazy(() =>
    import('./routes/institutions/submissions/index.lazy').then((d) => d.Route),
  )
const InstitutionsDashboardIndexLazyRoute =
  InstitutionsDashboardIndexLazyRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => InstitutionsRoute,
  } as any).lazy(() =>
    import('./routes/institutions/dashboard/index.lazy').then((d) => d.Route),
  )
const DashboardUsersIndexLazyRoute = DashboardUsersIndexLazyRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/users/index.lazy').then((d) => d.Route),
)
const DashboardTemplatesIndexLazyRoute =
  DashboardTemplatesIndexLazyRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/templates/index.lazy').then((d) => d.Route),
  )
const DashboardSubmissionsIndexLazyRoute =
  DashboardSubmissionsIndexLazyRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/submissions/index.lazy').then((d) => d.Route),
  )
const DashboardProductsIndexLazyRoute =
  DashboardProductsIndexLazyRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/index.lazy').then((d) => d.Route),
  )
const DashboardPhasesIndexLazyRoute =
  DashboardPhasesIndexLazyRouteImport.update({
    id: '/phases/',
    path: '/phases/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/phases/index.lazy').then((d) => d.Route),
  )
const DashboardInstitutionsIndexLazyRoute =
  DashboardInstitutionsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardInstitutionsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/institutions/index.lazy').then((d) => d.Route),
  )
const DashboardFormsIndexLazyRoute = DashboardFormsIndexLazyRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/forms/index.lazy').then((d) => d.Route),
)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsNotificationsLazyRoute =
  DashboardSettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSettingsDisplayLazyRoute =
  DashboardSettingsDisplayLazyRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/display.lazy').then((d) => d.Route),
  )
const DashboardSettingsAppearanceLazyRoute =
  DashboardSettingsAppearanceLazyRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/appearance.lazy').then((d) => d.Route),
  )
const DashboardSettingsAccountLazyRoute =
  DashboardSettingsAccountLazyRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/account.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/institutions': typeof InstitutionsRouteWithChildren
  '/dashboard/institutions': typeof DashboardInstitutionsRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard/': typeof DashboardIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountLazyRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceLazyRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayLazyRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsLazyRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexLazyRoute
  '/dashboard/institutions/': typeof DashboardInstitutionsIndexLazyRoute
  '/dashboard/phases': typeof DashboardPhasesIndexLazyRoute
  '/dashboard/products': typeof DashboardProductsIndexLazyRoute
  '/dashboard/submissions': typeof DashboardSubmissionsIndexLazyRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexLazyRoute
  '/dashboard/users': typeof DashboardUsersIndexLazyRoute
  '/institutions/dashboard': typeof InstitutionsDashboardIndexLazyRoute
  '/institutions/submissions': typeof InstitutionsSubmissionsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof DashboardIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountLazyRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceLazyRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayLazyRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsLazyRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexLazyRoute
  '/dashboard/institutions': typeof DashboardInstitutionsIndexLazyRoute
  '/dashboard/phases': typeof DashboardPhasesIndexLazyRoute
  '/dashboard/products': typeof DashboardProductsIndexLazyRoute
  '/dashboard/submissions': typeof DashboardSubmissionsIndexLazyRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexLazyRoute
  '/dashboard/users': typeof DashboardUsersIndexLazyRoute
  '/institutions/dashboard': typeof InstitutionsDashboardIndexLazyRoute
  '/institutions/submissions': typeof InstitutionsSubmissionsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/institutions': typeof InstitutionsRouteWithChildren
  '/dashboard/institutions': typeof DashboardInstitutionsRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/dashboard/': typeof DashboardIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountLazyRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceLazyRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayLazyRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsLazyRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexLazyRoute
  '/dashboard/institutions/': typeof DashboardInstitutionsIndexLazyRoute
  '/dashboard/phases/': typeof DashboardPhasesIndexLazyRoute
  '/dashboard/products/': typeof DashboardProductsIndexLazyRoute
  '/dashboard/submissions/': typeof DashboardSubmissionsIndexLazyRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexLazyRoute
  '/dashboard/users/': typeof DashboardUsersIndexLazyRoute
  '/institutions/dashboard/': typeof InstitutionsDashboardIndexLazyRoute
  '/institutions/submissions/': typeof InstitutionsSubmissionsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/institutions'
    | '/dashboard/institutions'
    | '/dashboard/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard/'
    | '/institutions/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/'
    | '/dashboard/forms'
    | '/dashboard/institutions/'
    | '/dashboard/phases'
    | '/dashboard/products'
    | '/dashboard/submissions'
    | '/dashboard/templates'
    | '/dashboard/users'
    | '/institutions/dashboard'
    | '/institutions/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/institutions'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings'
    | '/dashboard/forms'
    | '/dashboard/institutions'
    | '/dashboard/phases'
    | '/dashboard/products'
    | '/dashboard/submissions'
    | '/dashboard/templates'
    | '/dashboard/users'
    | '/institutions/dashboard'
    | '/institutions/submissions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/institutions'
    | '/dashboard/institutions'
    | '/dashboard/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/dashboard/'
    | '/institutions/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/'
    | '/dashboard/forms/'
    | '/dashboard/institutions/'
    | '/dashboard/phases/'
    | '/dashboard/products/'
    | '/dashboard/submissions/'
    | '/dashboard/templates/'
    | '/dashboard/users/'
    | '/institutions/dashboard/'
    | '/institutions/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InstitutionsRoute: typeof InstitutionsRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/institutions': {
      id: '/dashboard/institutions'
      path: '/institutions'
      fullPath: '/dashboard/institutions'
      preLoaderRoute: typeof DashboardInstitutionsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/institutions/submissions/': {
      id: '/institutions/submissions/'
      path: '/submissions'
      fullPath: '/institutions/submissions'
      preLoaderRoute: typeof InstitutionsSubmissionsIndexLazyRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/institutions/dashboard/': {
      id: '/institutions/dashboard/'
      path: '/dashboard'
      fullPath: '/institutions/dashboard'
      preLoaderRoute: typeof InstitutionsDashboardIndexLazyRouteImport
      parentRoute: typeof InstitutionsRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions/': {
      id: '/dashboard/submissions/'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/phases/': {
      id: '/dashboard/phases/'
      path: '/phases'
      fullPath: '/dashboard/phases'
      preLoaderRoute: typeof DashboardPhasesIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/institutions/': {
      id: '/dashboard/institutions/'
      path: '/'
      fullPath: '/dashboard/institutions/'
      preLoaderRoute: typeof DashboardInstitutionsIndexLazyRouteImport
      parentRoute: typeof DashboardInstitutionsRouteRoute
    }
    '/dashboard/forms/': {
      id: '/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms'
      preLoaderRoute: typeof DashboardFormsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/display': {
      id: '/dashboard/settings/display'
      path: '/display'
      fullPath: '/dashboard/settings/display'
      preLoaderRoute: typeof DashboardSettingsDisplayLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
  }
}

interface DashboardInstitutionsRouteRouteChildren {
  DashboardInstitutionsIndexLazyRoute: typeof DashboardInstitutionsIndexLazyRoute
}

const DashboardInstitutionsRouteRouteChildren: DashboardInstitutionsRouteRouteChildren =
  {
    DashboardInstitutionsIndexLazyRoute: DashboardInstitutionsIndexLazyRoute,
  }

const DashboardInstitutionsRouteRouteWithChildren =
  DashboardInstitutionsRouteRoute._addFileChildren(
    DashboardInstitutionsRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAccountLazyRoute: typeof DashboardSettingsAccountLazyRoute
  DashboardSettingsAppearanceLazyRoute: typeof DashboardSettingsAppearanceLazyRoute
  DashboardSettingsDisplayLazyRoute: typeof DashboardSettingsDisplayLazyRoute
  DashboardSettingsNotificationsLazyRoute: typeof DashboardSettingsNotificationsLazyRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAccountLazyRoute: DashboardSettingsAccountLazyRoute,
    DashboardSettingsAppearanceLazyRoute: DashboardSettingsAppearanceLazyRoute,
    DashboardSettingsDisplayLazyRoute: DashboardSettingsDisplayLazyRoute,
    DashboardSettingsNotificationsLazyRoute:
      DashboardSettingsNotificationsLazyRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardInstitutionsRouteRoute: typeof DashboardInstitutionsRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFormsIndexLazyRoute: typeof DashboardFormsIndexLazyRoute
  DashboardPhasesIndexLazyRoute: typeof DashboardPhasesIndexLazyRoute
  DashboardProductsIndexLazyRoute: typeof DashboardProductsIndexLazyRoute
  DashboardSubmissionsIndexLazyRoute: typeof DashboardSubmissionsIndexLazyRoute
  DashboardTemplatesIndexLazyRoute: typeof DashboardTemplatesIndexLazyRoute
  DashboardUsersIndexLazyRoute: typeof DashboardUsersIndexLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInstitutionsRouteRoute: DashboardInstitutionsRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFormsIndexLazyRoute: DashboardFormsIndexLazyRoute,
  DashboardPhasesIndexLazyRoute: DashboardPhasesIndexLazyRoute,
  DashboardProductsIndexLazyRoute: DashboardProductsIndexLazyRoute,
  DashboardSubmissionsIndexLazyRoute: DashboardSubmissionsIndexLazyRoute,
  DashboardTemplatesIndexLazyRoute: DashboardTemplatesIndexLazyRoute,
  DashboardUsersIndexLazyRoute: DashboardUsersIndexLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InstitutionsRouteChildren {
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  InstitutionsDashboardIndexLazyRoute: typeof InstitutionsDashboardIndexLazyRoute
  InstitutionsSubmissionsIndexLazyRoute: typeof InstitutionsSubmissionsIndexLazyRoute
}

const InstitutionsRouteChildren: InstitutionsRouteChildren = {
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  InstitutionsDashboardIndexLazyRoute: InstitutionsDashboardIndexLazyRoute,
  InstitutionsSubmissionsIndexLazyRoute: InstitutionsSubmissionsIndexLazyRoute,
}

const InstitutionsRouteWithChildren = InstitutionsRoute._addFileChildren(
  InstitutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InstitutionsRoute: InstitutionsRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
